let bodies = [
	{
		id: "hyperion",
		name: "Hypérion",
		englishName: "Hyperion",
		isPlanet: false,
		moons: null,
		semimajorAxis: 1500933,
		perihelion: 1466112,
		aphelion: 1535756,
		eccentricity: 0.123,
		inclination: 0.43,
		mass: [Object],
		vol: null,
		density: 0.55,
		gravity: 0,
		escape: 0,
		meanRadius: 266,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "328×260×214",
		sideralOrbit: 21.28,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "William Cranch Bond, George Phillips Bond",
		discoveryDate: "16/09/1848",
		alternativeName: "",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https:api.le-systeme-solaire.net/rest/bodies/hyperion",
	},
	{
		id: "japet",
		name: "Japet",
		englishName: "Iapetus",
		isPlanet: false,
		moons: null,
		semimajorAxis: 3560854,
		perihelion: 3460068,
		aphelion: 3661612,
		eccentricity: 0.0283,
		inclination: 14.72,
		mass: [Object],
		vol: null,
		density: 1.09,
		gravity: 0,
		escape: 0,
		meanRadius: 1471.2,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 79.33,
		sideralRotation: 1735.92,
		aroundPlanet: [Object],
		discoveredBy: "Jean-Dominique Cassini",
		discoveryDate: "25/10/1671",
		alternativeName: "",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/japet",
	},
	{
		id: "phoebe",
		name: "Phœbé",
		englishName: "Phoebe",
		isPlanet: false,
		moons: null,
		semimajorAxis: 12944300,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.164,
		inclination: 174.8,
		mass: [Object],
		vol: null,
		density: 1.64,
		gravity: 0,
		escape: 0,
		meanRadius: 214.4,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "230×220×210",
		sideralOrbit: 548.2,
		sideralRotation: 9.2736,
		aroundPlanet: [Object],
		discoveredBy: "William Henry Pickering",
		discoveryDate: "17/03/1899",
		alternativeName: "",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/phoebe",
	},
	{
		id: "janus",
		name: "Janus",
		englishName: "Janus",
		isPlanet: false,
		moons: null,
		semimajorAxis: 151500,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.007,
		inclination: 0.14,
		mass: [Object],
		vol: null,
		density: 0.63,
		gravity: 0,
		escape: 0,
		meanRadius: 89.5,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "195×194×152",
		sideralOrbit: 0.7,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Audouin Dollfus",
		discoveryDate: "15/12/1966",
		alternativeName: "S/1980 S 1",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/janus",
	},
	{
		id: "epimethee",
		name: "Epiméthée",
		englishName: "Epimetheus",
		isPlanet: false,
		moons: null,
		semimajorAxis: 151400,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.009,
		inclination: 0.34,
		mass: [Object],
		vol: null,
		density: 0.64,
		gravity: 0,
		escape: 0,
		meanRadius: 113.4,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "116×117×106",
		sideralOrbit: 0.69,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Richard L. Walker",
		discoveryDate: "18/12/1966",
		alternativeName: "S/1980 S 3",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/epimethee",
	},
	{
		id: "helene",
		name: "Hélène",
		englishName: "Helene",
		isPlanet: false,
		moons: null,
		semimajorAxis: 377396,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.0022,
		inclination: 0.199,
		mass: null,
		vol: null,
		density: 1.3,
		gravity: 0,
		escape: 0,
		meanRadius: 17.6,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "43.4 x 38.2 x 26",
		sideralOrbit: 2.736,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Pierre Laques, Raymond Despiau, Jean Lecacheux",
		discoveryDate: "01/03/1980",
		alternativeName: "S/1980 S 6",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/helene",
	},
	{
		id: "telesto",
		name: "Télesto",
		englishName: "Telesto",
		isPlanet: false,
		moons: null,
		semimajorAxis: 294720,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.001,
		inclination: 1.158,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 12.4,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "30×23×14",
		sideralOrbit: 1.89,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy:
			"Bradford A. Smith, Harold J. Reitsema, Stephen M. Larson, John W. Fountain",
		discoveryDate: "08/04/1980",
		alternativeName: "S/1980 S 13",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/telesto",
	},
	{
		id: "calypso",
		name: "Calypso",
		englishName: "Calypso",
		isPlanet: false,
		moons: null,
		semimajorAxis: 294720,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.001,
		inclination: 1.473,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 10.7,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "31×24×21",
		sideralOrbit: 1.89,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy:
			"Dan Pascu, P. Kenneth Seidelmann, William A. Baum, Douglas Currie",
		discoveryDate: "13/03/1980",
		alternativeName: "S/1980 S 25",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/calypso",
	},
	{
		id: "atlas",
		name: "Atlas",
		englishName: "Atlas",
		isPlanet: false,
		moons: null,
		semimajorAxis: 137700,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0,
		inclination: 0.3,
		mass: [Object],
		vol: null,
		density: 0.5,
		gravity: 0,
		escape: 0,
		meanRadius: 15.1,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "42×36×18",
		sideralOrbit: 0.602,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Richard J. Terrile",
		discoveryDate: "12/11/1980",
		alternativeName: "S/1980 S 28",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/atlas",
	},
	{
		id: "promethee",
		name: "Prométhée",
		englishName: "Prometheus",
		isPlanet: false,
		moons: null,
		semimajorAxis: 139400,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.00204,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 0.48,
		gravity: 0,
		escape: 0,
		meanRadius: 43.1,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "133×79×61",
		sideralOrbit: 0.613,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Stewart A. Collins, D. Carlson",
		discoveryDate: "??/10/1980",
		alternativeName: "S/1980 S 27",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/promethee",
	},
	{
		id: "pandore",
		name: "Pandore",
		englishName: "Pandora",
		isPlanet: false,
		moons: null,
		semimajorAxis: 141700,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.0042,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 0.49,
		gravity: 0,
		escape: 0,
		meanRadius: 40.7,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "103×80×64",
		sideralOrbit: 0.629,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Stewart A. Collins",
		discoveryDate: "??/10/1980",
		alternativeName: "S/1980 S 26",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/pandore",
	},
	{
		id: "pan",
		name: "Pan",
		englishName: "Pan",
		isPlanet: false,
		moons: null,
		semimajorAxis: 133600,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 0.42,
		gravity: 0,
		escape: 0,
		meanRadius: 14.1,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "35×32×21",
		sideralOrbit: 0.575,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Mark R. Showalter",
		discoveryDate: "22/08/1981",
		alternativeName: "S/1981 S 13",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/pan",
	},
	{
		id: "ymir",
		name: "Ymir",
		englishName: "Ymir",
		isPlanet: false,
		moons: null,
		semimajorAxis: 23040000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.187,
		inclination: 167.9,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 9,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 1315.4,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Brett J. Gladman",
		discoveryDate: "07/08/2000",
		alternativeName: "S/2000 S 1",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/ymir",
	},
	{
		id: "paaliaq",
		name: "Paaliaq",
		englishName: "Paaliaq",
		isPlanet: false,
		moons: null,
		semimajorAxis: 15200000,
		perihelion: 6908035,
		aphelion: 23139965,
		eccentricity: 0.364,
		inclination: 47.2,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 10,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 686.9,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "07/08/2000",
		alternativeName: "S/2000 S 2",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/paaliaq",
	},
	{
		id: "tarvos",
		name: "Tarvos",
		englishName: "Tarvos",
		isPlanet: false,
		moons: null,
		semimajorAxis: 17983000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.531,
		inclination: 33.8,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 7,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 926.2,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 4",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/tarvos",
	},
	{
		id: "ijiraq",
		name: "Ijiraq",
		englishName: "Ijiraq",
		isPlanet: false,
		moons: null,
		semimajorAxis: 11124000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.316,
		inclination: 49.1,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 5,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 451.4,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 6",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/ijiraq",
	},
	{
		id: "suttungr",
		name: "Suttungr",
		englishName: "Suttungr",
		isPlanet: false,
		moons: null,
		semimajorAxis: 19459000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.114,
		inclination: 175.8,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 3,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 1016.7,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 12",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/suttungr",
	},
	{
		id: "kiviuq",
		name: "Kiviuq",
		englishName: "Kiviuq",
		isPlanet: false,
		moons: null,
		semimajorAxis: 11111000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.334,
		inclination: 48.7,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 7,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 449.2,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Brett J. Gladman",
		discoveryDate: "07/08/2000",
		alternativeName: "S/2000 S 5",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/kiviuq",
	},
	{
		id: "mundilfari",
		name: "Mundilfari",
		englishName: "Mundilfari",
		isPlanet: false,
		moons: null,
		semimajorAxis: 18685000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.21,
		inclination: 169.4,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 3,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 952.6,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 9",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/mundilfari",
	},
	{
		id: "albiorix",
		name: "Albiorix",
		englishName: "Albiorix",
		isPlanet: false,
		moons: null,
		semimajorAxis: 16182000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.469,
		inclination: 34,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 13,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 783.5,
		sideralRotation: 13.32,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "09/11/2000",
		alternativeName: "S/2000 S 11",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/albiorix",
	},
	{
		id: "skathi",
		name: "Skathi",
		englishName: "Skathi",
		isPlanet: false,
		moons: null,
		semimajorAxis: 15541000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.27,
		inclination: 148.5,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 3,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 728.2,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 8",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/skathi",
	},
	{
		id: "erriapo",
		name: "Erriapo",
		englishName: "Erriapus",
		isPlanet: false,
		moons: null,
		semimajorAxis: 17343000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.474,
		inclination: 34.6,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 4,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 871.2,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 10",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/erriapo",
	},
	{
		id: "siarnaq",
		name: "Siarnaq",
		englishName: "Siarnaq",
		isPlanet: false,
		moons: null,
		semimajorAxis: 17531000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.295,
		inclination: 45.6,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 16,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 895.6,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 3",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/siarnaq",
	},
	{
		id: "thrymr",
		name: "Thrymr",
		englishName: "Thrymr",
		isPlanet: false,
		moons: null,
		semimajorAxis: 20474000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.47,
		inclination: 175,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 3,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 1094.3,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "John J. Kavelaars, Brett J. Gladman",
		discoveryDate: "23/09/2000",
		alternativeName: "S/2000 S 7",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/thrymr",
	},
	{
		id: "narvi",
		name: "Narvi",
		englishName: "Narvi",
		isPlanet: false,
		moons: null,
		semimajorAxis: 19007000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.431,
		inclination: 145.8,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 3,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 1003.9,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Scott S. Sheppard, David C. Jewitt, Jan Kleyna",
		discoveryDate: "05/02/2003",
		alternativeName: "S/2003 S 1",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/narvi",
	},
	{
		id: "methone",
		name: "Méthone",
		englishName: "Methone",
		isPlanet: false,
		moons: null,
		semimajorAxis: 194000,
		perihelion: 194421,
		aphelion: 194459,
		eccentricity: 0.0001,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 1.6,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "",
		sideralOrbit: 1.01,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Carolyn C. Porco, Sébastien Charnoz",
		discoveryDate: "01/06/2004",
		alternativeName: "S/2004 S 1",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/methone",
	},
	{
		id: "pallene",
		name: "Pallène",
		englishName: "Pallene",
		isPlanet: false,
		moons: null,
		semimajorAxis: 211000,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.004,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 2.5,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "5×4×4",
		sideralOrbit: 1.14,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Carolyn C. Porco, Sébastien Charnoz",
		discoveryDate: "01/06/2004",
		alternativeName: "S/2004 S 2",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/pallene",
	},
	{
		id: "pollux",
		name: "Pollux",
		englishName: "Polydeuces",
		isPlanet: false,
		moons: null,
		semimajorAxis: 377390,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0.018,
		inclination: 0.1705,
		mass: [Object],
		vol: null,
		density: 1,
		gravity: 0,
		escape: 0,
		meanRadius: 2,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "3×2×2",
		sideralOrbit: 2.737,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Carolyn C. Porco",
		discoveryDate: "21/10/2004",
		alternativeName: "S/2004 S 5",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/pollux",
	},
	{
		id: "daphnis",
		name: "Daphnis",
		englishName: "Daphnis",
		isPlanet: false,
		moons: null,
		semimajorAxis: 136500,
		perihelion: 0,
		aphelion: 0,
		eccentricity: 0,
		inclination: 0,
		mass: [Object],
		vol: null,
		density: 0.34,
		gravity: 0,
		escape: 0,
		meanRadius: 3.8,
		equaRadius: 0,
		polarRadius: 0,
		flattening: 0,
		dimension: "9×8×6",
		sideralOrbit: 0.594,
		sideralRotation: 0,
		aroundPlanet: [Object],
		discoveredBy: "Carolyn C. Porco",
		discoveryDate: "01/05/2009",
		alternativeName: "S/2005 S 1",
		axialTilt: 0,
		avgTemp: 0,
		mainAnomaly: 0,
		argPeriapsis: 0,
		longAscNode: 0,
		bodyType: "Moon",
		rel: "https: //api.le-systeme-solaire.net/rest/bodies/daphnis",
	},
];
